FROM debian:13.1

ENV DEBIAN_FRONTEND=noninteractive
ENV UV_INSTALLER_NO_MODIFY_PATH=1
ENV PATH="/root/.local/bin:${PATH}"

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        ca-certificates \
        curl \
        git \
        python3 \
        python3-pip \
        python3-venv \
        build-essential && \
    rm -rf /var/lib/apt/lists/*

RUN curl -LsSf https://astral.sh/uv/install.sh | sh

WORKDIR /app

CMD ["/bin/bash"]
